displayName: ScaleWaker
type: middleware

import: "nomad_scale_to_zero/traefik-plugin"

summary: "Scale Nomad jobs to 1 on demand and record activity"

testData:
  serviceName: "echo-s2z"
  jobName: "echo-s2z"
  groupName: "main"
  nomadAddr: "http://127.0.0.1:4646"
  consulAddr: "http://127.0.0.1:8500"
  activityStore: "consul"
  timeout: "30s"
