{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nscale.secretName" . }}
  labels:
    {{- include "nscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
stringData:
  {{- if .Values.secrets.nomadToken }}
  {{ .Values.secrets.secretKeys.nomadToken }}: {{ .Values.secrets.nomadToken | quote }}
  {{- end }}
  {{- if .Values.secrets.consulToken }}
  {{ .Values.secrets.secretKeys.consulToken }}: {{ .Values.secrets.consulToken | quote }}
  {{- end }}
{{- end }}
