http:
  routers:
    s2z-fallback:
      rule: "HostRegexp(`^[a-z0-9-]+\\.localhost$`)"
      priority: 1
      entryPoints:
        - http
      service: s2z-fallback
      middlewares:
        - scalewaker-fallback

  services:
    s2z-fallback:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:1"

  middlewares:
    scalewaker-fallback:
      plugin:
        scalewaker:
          timeout: "30s"
